"""리스크 승인/거부 사유 코드 (API·로그·감사 공통)."""

from __future__ import annotations

from enum import StrEnum


class RiskReasonCode(StrEnum):
    OK = "OK"
    OK_SELL = "OK_SELL"
    OK_BUY = "OK_BUY"
    OK_WEIGHT = "OK_WEIGHT"
    OK_REGIME_BEARISH_BUY_CONSERVATIVE = "OK_REGIME_BEARISH_BUY_CONSERVATIVE"

    TRADING_COOLDOWN_ACTIVE = "TRADING_COOLDOWN_ACTIVE"
    SYSTEM_OFF_TOTAL_LOSS = "SYSTEM_OFF_TOTAL_LOSS"
    HALT_DAILY_LOSS = "HALT_DAILY_LOSS"
    HALT_ROLLING_LOSS_LIMIT = "HALT_ROLLING_LOSS_LIMIT"

    TRADING_COOLDOWN_REQUIRED_ADAPTIVE = "TRADING_COOLDOWN_REQUIRED_ADAPTIVE"
    ADAPTIVE_NEW_ENTRY_LIMIT = "ADAPTIVE_NEW_ENTRY_LIMIT"
    ADAPTIVE_ENTRY_FILTER_BLOCK = "ADAPTIVE_ENTRY_FILTER_BLOCK"

    BLOCK_REGIME_HIGH_VOLATILITY_NEW_ENTRY = "BLOCK_REGIME_HIGH_VOLATILITY_NEW_ENTRY"
    BLOCK_REGIME_BEARISH_NEW_ENTRY_LIMIT = "BLOCK_REGIME_BEARISH_NEW_ENTRY_LIMIT"
    BLOCK_BAD_MARKET_FILTER = "BLOCK_BAD_MARKET_FILTER"

    MISSING_STOP_LOSS = "MISSING_STOP_LOSS"
    BLOCK_REGIME_BEARISH_STOP_LOSS_TOO_WIDE = "BLOCK_REGIME_BEARISH_STOP_LOSS_TOO_WIDE"
    REENTRY_COOLDOWN = "REENTRY_COOLDOWN"
    INVALID_ORDER_PRICE = "INVALID_ORDER_PRICE"
    INVALID_EQUITY = "INVALID_EQUITY"

    MAX_POSITIONS_EXCEEDED = "MAX_POSITIONS_EXCEEDED"
    BLOCK_REGIME_BEARISH_MAX_POSITIONS = "BLOCK_REGIME_BEARISH_MAX_POSITIONS"
    POSITION_WEIGHT_TOO_HIGH = "POSITION_WEIGHT_TOO_HIGH"
    BLOCK_REGIME_BEARISH_POSITION_WEIGHT = "BLOCK_REGIME_BEARISH_POSITION_WEIGHT"
    POSITION_WEIGHT_TOO_LOW = "POSITION_WEIGHT_TOO_LOW"

    ORDER_QUANTITY_INVALID = "ORDER_QUANTITY_INVALID"
    ORDER_NOTIONAL_EXCEEDS_CAP = "ORDER_NOTIONAL_EXCEEDS_CAP"
    SYMBOL_NOT_ALLOWED = "SYMBOL_NOT_ALLOWED"
